
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Темы курса","2bc58982-19aa-49ef-bae2-8aaa5d13b967")]
    public class Темы_курса
        {
		//#video 1y1dZ7T9yeA

        }
}