
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Почему важна компьютерная безопасность","26bd758d-c6f4-4102-839e-a5b68e14b3c2")]
    public class Почему_важна_компьютерная_безопасность
        {
		//#video mR4ZfA8NT8Y

        }
}