
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Классический CTF","55531877-74a0-4624-869f-96f8cd9a2e25")]
    public class Классический_CTF
        {
		//#video 8FP4bVp6UVg

        }
}