
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"CTF-jeopardy","27f42d11-1fec-4139-8c72-d3e4fb15bf4a")]
    public class CTF_jeopardy
        {
		//#video 0OvOQmgYceI

        }
}