
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"А если картинка в JPEG","0ac74cc4-9429-4087-bc2f-388f567d62bd")]
    public class А_если_картинка_в_JPEG
        {
		//#video EvNCqfCJgCc

        }
}