
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Стеганография в звуке и видео","e44c0c68-f260-467b-a262-ad5f59addc7e")]
    public class Стеганография_в_звуке_и_видео
        {
		//#video DlTKpxWMrBQ

        }
}