
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Цифровые водяные знаки","5fc8f334-08fc-4d86-a974-26749f7a497f")]
    public class Цифровые_водяные_знаки
        {
		//#video dkdDZjKG18E

        }
}