
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Практика","c0e30051-4c3a-41f0-961a-65cf7c6dbaf9")]
    public class Практика
        {
		//#video aIhL-04oQjU

        }
}