
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Заключение","eda63641-e069-421c-ba43-3ce811ee655a")]
    public class Заключение
        {
		//#video zX-2NMNLOfc

        }
}