
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Инъекции","283ec4e7-203e-42b5-8227-a887e307b51a")]
    public class Инъекции
        {
		//#video dJkgxtmwpdw

        }
}