
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"SQL-инъекции","61825d93-82e6-4db5-ae21-6fc9aae4e315")]
    public class SQL_инъекции
        {
		//#video Zqj_Z5eR_TY

        }
}