
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"SQL-инъекции с UNION","e9de4b61-ae31-4aee-a860-c6db495e8e2f")]
    public class SQL_инъекции_с_UNION
        {
		//#video oG2CUQb1wPs

        }
}