
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Группировка, сортировка и работа с файлами","e4c11062-7ed1-42b9-815d-e39a455ccc02")]
    public class Группировка__сортировка_и_работа_с_файлами
        {
		//#video ppUkgKIodTI

        }
}