
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Экранирование символов","2a37b4c1-4666-4808-b4e3-6cc03be72a2d")]
    public class Экранирование_символов
        {
		//#video VBpnLO-x6kM

        }
}