
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Множественные запросы","8adcc22b-abbe-4a36-8bd6-88c4f953a54a")]
    public class Множественные_запросы
        {
		//#video NxiYHiXUp6g

        }
}