
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Слепые инъекции","bbbc041f-10fe-4663-99df-48e568783624")]
    public class Слепые_инъекции
        {
		//#video bchpaHVbXjc

        }
}