
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"NoSQL ","091326fc-02a8-425c-8b80-09a9bed6ce19")]
    public class NoSQL_
        {
		//#video PHaMtKdXFvo

        }
}