
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"XPath","a8ebb60c-0fce-4d80-b46a-6872c82bfaf0")]
    public class XPath
        {
		//#video Q2hu49y-pI4

        }
}