
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Инъекции в командах ОС","e34d0b18-fb8c-4039-85a2-5ca392bc66f0")]
    public class Инъекции_в_командах_ОС
        {
		//#video h3glLxdeddA

        }
}