
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Инъекции в HTTP-заголовки","1a9b7825-704d-4d1e-bc78-a697386da3dd")]
    public class Инъекции_в_HTTP_заголовки
        {
		//#video qUEcRocH9z4

        }
}