
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Заключение","89ab29cb-4715-4a9c-84cd-2131399d394a")]
    public class Заключение1
        {
		//#video aYeUgoEn00Y

        }
}