
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Протоколы прикладного уровня","c916589a-8df8-4173-ac1f-c973370a3dfa")]
    public class Протоколы_прикладного_уровня
        {
		//#video 9H_8gUKNCZ8

        }
}