
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Протокол DNS","9df2f428-cf35-4a91-9350-b3bf6a635abd")]
    public class Протокол_DNS
        {
		//#video VXTf9i-Gqsw

        }
}