
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Иерархия NS-серверов","b07a0f80-a40a-4c16-91c2-7ba49bd97449")]
    public class Иерархия_NS_серверов
        {
		//#video EXuRhfztWdo

        }
}