
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Отравления кэша в DNS","634ff379-c533-4722-9b9e-b9d8ca4aa82d")]
    public class Отравления_кэша_в_DNS
        {
		//#video YAHVW7nRJ4U

        }
}