
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Дополнительные подробности о DNS","ecb00bac-3f60-4a74-b9ef-25ce54c4cb67")]
    public class Дополнительные_подробности_о_DNS
        {
		//#video y1WmetnJm70

        }
}