
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Протокол FTP","96416927-9ffa-494f-a649-2c0f7f64950d")]
    public class Протокол_FTP
        {
		//#video J5N94PD77HY

        }
}