
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Дополнительные подробности о FTP","bf2f44ce-6b9c-4e3d-aada-12edd5414156")]
    public class Дополнительные_подробности_о_FTP
        {
		//#video XnWb0YV7dk4

        }
}