
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"История HTTP","5ad7c7fc-d551-416b-b6c7-f844de0b89c3")]
    public class История_HTTP
        {
		//#video eOn10ip13EA

        }
}