
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Структура HTTP","6ee91c90-1e81-44d2-92fd-b679382c0e39")]
    public class Структура_HTTP
        {
		//#video 0G6cnLFoaNA

        }
}