
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Методы HTTP","062b52e2-c3ef-405e-b116-6172f6d6b387")]
    public class Методы_HTTP
        {
		//#video EcbD6ZQIuyg

        }
}