
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Заголовки, часть 1","b1f4cccd-cee7-4482-976d-ceb60d326272")]
    public class Заголовки__часть_1
        {
		//#video KF8VSy1qH7o

        }
}