
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Заголовки, часть 2","aa039f98-fcdf-4c2b-9beb-90aa5c74c8a3")]
    public class Заголовки__часть_2
        {
		//#video OQCJxmDQtGQ

        }
}