
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Авторизация и аутентификация","b1504c3e-fb8d-4bf1-85cb-fb85336c7c9e")]
    public class Авторизация_и_аутентификация
        {
		//#video pyG_hkaVfDc

        }
}