
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Протокол HTTPS","b8744320-0270-4d1c-aee3-33375e48e9bd")]
    public class Протокол_HTTPS
        {
		//#video 2K_CsrFIMII

        }
}