
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Протокол CGI","67dc4001-31bb-4192-b7cc-b245bf62bf14")]
    public class Протокол_CGI
        {
		//#video pN5Tfizb6oA

        }
}