
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"HTML и формы","55ee9893-66a4-4803-befe-116a7996d16a")]
    public class HTML_и_формы
        {
		//#video owz6EGtAYEI

        }
}