
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Атаки на HTML","03c0202b-0aeb-4789-be91-04e7a0a2a9b3")]
    public class Атаки_на_HTML
        {
		//#video F-RRLHtNPa4

        }
}