
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Хэш-функции","248cee8f-1f7f-410a-a09a-93f8935b82ad")]
    public class Хэш_функции
        {
		//#video WhNV1mrDoeo

        }
}