
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Применение хэш-функций","dae458e2-78bf-438f-8e69-258491c006f9")]
    public class Применение_хэш_функций
        {
		//#video O7oJzV1-jRA

        }
}