
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Применение криптостойких хэш-функций, часть 2","e0e26cd9-0910-4e19-be6c-cea609cc5c88")]
    public class Применение_криптостойких_хэш_функций__часть_2
        {
		//#video tIDvkcLCwFw

        }
}