
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Архитектура Bitcoin","ca0b5c85-1ccb-4e93-825c-901253802771")]
    public class Архитектура_Bitcoin
        {
		//#video gjeyGlR44nQ

        }
}