
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Экономика Bitcoin","cc2f600c-9af5-486b-91ec-fd9308005f5c")]
    public class Экономика_Bitcoin
        {
		//#video 8wjLTrjR-5c

        }
}