
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"История криптографии","952ab6b0-cfe3-40fa-ba7e-0509326049ce")]
    public class История_криптографии
        {
		//#video pI0JKirxn8U

        }
}