
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Алгоритм Диффи-Хеллмана","403f3218-abec-47e2-bcfb-4f302b38128a")]
    public class Алгоритм_Диффи_Хеллмана
        {
		//#video Ed6oWRkEgaw

        }
}