
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Корректность алгоритма RSA","1f6d91df-7d89-4b30-9e60-47bef586d6dc")]
    public class Корректность_алгоритма_RSA
        {
		//#video -gIqk9hs52c

        }
}