
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Электронно-цифровая подпись","a7294d8e-4796-4991-b20b-781e855953c8")]
    public class Электронно_цифровая_подпись
        {
		//#video Ow5encTf8lg

        }
}