
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Заключительные положения","85fc6105-12a0-4023-be20-5918da742c76")]
    public class Заключительные_положения
        {
		//#video 4sEkOfBNQmQ

        }
}