
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"GNU, FSF","942e5bdf-e8ac-4b71-bd41-6b6907047a9f")]
    public class GNU__FSF
        {
		//#video 5Hf4imBLtw0

        }
}