
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Unix Way","dd4267c3-d178-4644-a07d-c30bed4b2d21")]
    public class Unix_Way
        {
		//#video Zm0xjc14obQ

        }
}