
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Пользователи","3545dbbb-e990-4401-9892-3bf001bedd6c")]
    public class Пользователи
        {
		//#video Y6153iteGiU

        }
}