
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Команды Linux","199bdd47-8111-427d-8677-00e434745302")]
    public class Команды_Linux
        {
		//#video 2OV4d9-aXao
		/*
		Досадная оплошность: на самом деле опция -f для команды rm отключает подтверждение удаления файлов.
		*/
	}
}