
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Виртуальные машины","fbd2a4df-0e0a-4961-ba81-852fb97b4be5")]
    public class Виртуальные_машины
        {
		//#video 6_4y__6aOtQ

        }
}