
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Стэк OSI","ed50edd9-688d-4b94-bdc1-9f899880e4eb")]
    public class Стэк_OSI
        {
		//#video UleXPiLMWU8

        }
}