
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Физический уровень","00848dda-cbdf-489d-869c-67845796569e")]
    public class Физический_уровень
        {
		//#video 48qMvnQQrso

        }
}