
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Канальный уровень","cac04028-159e-4c26-897e-dc6748b114ff")]
    public class Канальный_уровень
        {
		//#video hJOF5u85JHc

        }
}