
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Сетевой уровень. IP-адреса","37b9f0b8-cdf2-43fd-9ac5-a943a0a47e71")]
    public class Сетевой_уровень__IP_адреса
        {
		//#video ihBlDnfUdVk

        }
}