
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Протокол DHCP","1cb2c4d2-1f05-4223-a7de-8549e2f0cab3")]
    public class Протокол_DHCP
        {
		//#video DBeeBCvovzE
		/*
		Досадная оплошность: на двух слайдах и в моей речи допущена ошибка. Пакет называется ACK, а не PACK. Будьте внимательны и не ведитесь на подделки!
		*/
	}
}
 