
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Протокол DHCP","1cb2c4d2-1f05-4223-a7de-8549e2f0cab3")]
    public class Протокол_DHCP
        {
		//#video DBeeBCvovzE

        }
}