
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Протокол ARP","62b09b31-3ed0-4e24-9169-1240b336dccf")]
    public class Протокол_ARP
        {
		//#video 7pEt99sKVio

        }
}