
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Маршрутизация","dcc16070-0bf8-4e94-96ee-4287940e167a")]
    public class Маршрутизация
        {
		//#video _B9xAFEcfDg

        }
}