
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Протокол TCP","753844e2-97f4-496d-8aec-26ced5386357")]
    public class Протокол_TCP
        {
		//#video RRXxTkbvZaQ

        }
}