
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Порты","e0c9669f-4a74-46fa-81d6-2a49023512bb")]
    public class Порты
        {
		//#video rJdRw3b-LxY

        }
}