
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Протокол NAT","3ac1853a-6dec-408e-a9c9-1c1b0688e36e")]
    public class Протокол_NAT
        {
		//#video w7bXl7ECinc

        }
}