
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Практика, часть 1","9010dd2b-157f-4384-8d12-26ba98433211")]
    public class Практика__часть_1
        {
		//#video HfYQKv8Ws_A

        }
}