
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Практика, часть 2","23de7b8f-8a5d-493c-82dc-16b72fd4b15d")]
    public class Практика__часть_2
        {
		//#video nPJ7GwRyVZI

        }
}