
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Криптографическая хеш-функция","7a6d1653-7865-490d-8209-8165fe65591b")]
    public class Криптографическая_хеш_функция
        {
		//#video CRQnC44OO_A

        }
}