
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Применение криптографических хеш-функций, часть 1","36456d24-9129-4c38-a8ff-25dc62b66069")]
    public class Применение_криптографических_хеш_функций__часть_1
        {
		//#video mlNsulIQdTk

        }
}