
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Архитектура компьютера","e1ab44a2-c4c4-45f5-807b-cbea25dd743d")]
    public class Архитектура_компьютера
        {
		//#video 0mcNIH6z9vQ
        }
}