
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Принцип Фон Неймана","7f2512c2-5df5-44c0-b787-6c439d7a5154")]
    public class Принцип_Фон_Неймана
        {
		//#video 4B30SevpHvY
        }
}