
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Регистры процессоров","552b9070-0243-4655-989f-5f856c189084")]
    public class Регистры_процессоров
        {
		//#video QBA_tMfTop0
        }
}