
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Ассемблер","21f4cf4e-bb28-4778-8e82-9cc57141ac41")]
    public class Ассемблер
        {
		//#video a5P7ZOZftRU
        }
}