
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Команда MOV","f27ceaf2-3926-42e3-a862-e04c6771b0cf")]
    public class Команда_MOV
        {
		//#video yXQ4Q6pS-XM
        }
}