
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Арифметические и логические операции","93f658c4-84bd-4312-b8ec-8b0d5945962f")]
    public class Арифметические_и_логические_операции
        {
		//#video fulaXZPLDw0
        }
}