
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Знаковые числа","49856ebe-f862-4272-b041-ad4d688cba99")]
    public class Знаковые_числа
        {
		//#video 0_x7ys_Ckd8
        }
}