
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Безусловный переход","45cbad06-e7b0-4c02-b74d-7802b4d09d0e")]
    public class Безусловный_переход
        {
		//#video H-a9bGdmN1k
        }
}