
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Управление выполнением программы","0a3ba148-7495-4014-9065-8f59dc43aac1")]
    public class Управление_выполнением_программы
        {
		//#video u7yY6X-ZDko
        }
}