
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Функции","e2cfed6d-3ca8-4eac-8c70-766b66fac55e")]
    public class Функции
        {
		//#video X6Ah1ZCZj-A
        }
}