
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Структура исполняемого файла","e171284d-0962-4e63-b370-8036a3bce1eb")]
    public class Структура_исполняемого_файла
        {
		//#video -gEyUcBo7YQ
        }
}