
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Введение в Reverse Engineering","88892f91-997b-4739-a305-ada5ffff7439")]
    public class Введение_в_Reverse_Engineering
        {
		//#video X4JjFF3bSr0
        }
}