
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Форматы исполняемых файлов","d93e0e1b-95ec-4ee1-8e18-696079347b6c")]
    public class Форматы_исполняемых_файлов
        {
		//#video i4wptvkEwHw
        }
}