
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Как устроен РЕ-файл","6a0773c7-1aa2-44b3-af3e-3f53691a55a7")]
    public class Как_устроен_РЕ_файл
        {
		//#video -votu30GtkM
        }
}