
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Паттерны исполняемого кода","a985c48c-020b-4e09-a3f3-5658205ab1a7")]
    public class Паттерны_исполняемого_кода
        {
		//#video gD9U0wAdWFs
        }
}