
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Объектно-ориентированное программирование","26f3391a-2792-430d-8398-8e7312dfd0fc")]
    public class Объектно_ориентированное_программирование
        {
		//#video RcrSby2hA78
        }
}