
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Пакеры","344de5f8-8657-420c-a5a2-e2e648739ab6")]
    public class Пакеры
        {
		//#video 5r0-Yadh944
        }
}