
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Антиотладка","ab9abdef-959a-4d31-b7af-40255df35d50")]
    public class Антиотладка
        {
		//#video GPO_1pTqxhc
        }
}