
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Введение в бинарные уязвимости","4895ff12-8a51-45d1-a32e-956347066598")]
    public class Введение_в_бинарные_уязвимости
        {
		//#video kZBt15ineJ8
        }
}