
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Отладчик GDB","612bbc3f-cbb4-4d0b-a2c4-6f571c1416d5")]
    public class Отладчик_GDB
        {
		//#video RCD_x--emVE
        }
}