
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Переполнение стека","3bda1c2c-c2a1-4fb0-9146-fccc47daf93b")]
    public class Переполнение_стека
        {
		//#video 7votHlnZ3PE
        }
}