
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Исполнение кода, шеллкод","8feb1864-c3c8-462b-b226-e1b40f17b3c8")]
    public class Исполнение_кода__шеллкод
        {
		//#video zkAEi9zbB_0
        }
}