
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Уязвимость форматной строки","4905e6d3-0b7a-426c-8555-0b45f4b5207a")]
    public class Уязвимость_форматной_строки
        {
		//#video Q5rUgkXrzyQ
        }
}