
//automatically generated by Tuto
using uLearn;
namespace Hackerdom 
{
    [Slide(@"Запись произвольной памяти","1196f4d3-49ad-4314-bc08-e469e1cc640c")]
    public class Запись_произвольной_памяти
        {
		//#video RhMjPXHytZQ
        }
}